#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tpm2-abrmd
Version  : 2.0.3
Release  : 2
URL      : https://github.com/tpm2-software/tpm2-abrmd/releases/download/2.0.3/tpm2-abrmd-2.0.3.tar.gz
Source0  : https://github.com/tpm2-software/tpm2-abrmd/releases/download/2.0.3/tpm2-abrmd-2.0.3.tar.gz
Summary  : TCTI library for communicating with the TPM2 access broker / resource manager daemon (tabrmd).
Group    : Development/Tools
License  : BSD-2-Clause
Requires: tpm2-abrmd-bin = %{version}-%{release}
Requires: tpm2-abrmd-config = %{version}-%{release}
Requires: tpm2-abrmd-data = %{version}-%{release}
Requires: tpm2-abrmd-lib = %{version}-%{release}
Requires: tpm2-abrmd-license = %{version}-%{release}
Requires: tpm2-abrmd-man = %{version}-%{release}
BuildRequires : pkgconfig(cmocka)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(tss2-sys)
BuildRequires : valgrind

%description
[![Build Status](https://travis-ci.org/tpm2-software/tpm2-abrmd.svg?branch=master)](https://travis-ci.org/tpm2-software/tpm2-abrmd)
[![Coverity Scan](https://img.shields.io/coverity/scan/3997.svg)](https://scan.coverity.com/projects/01org-tpm2-abrmd)
[![Coverage Status](https://img.shields.io/coveralls/github/tpm2-software/tpm2-abrmd/master.svg)](https://coveralls.io/github/tpm2-software/tpm2-abrmd?branch=master)

%package bin
Summary: bin components for the tpm2-abrmd package.
Group: Binaries
Requires: tpm2-abrmd-data = %{version}-%{release}
Requires: tpm2-abrmd-config = %{version}-%{release}
Requires: tpm2-abrmd-license = %{version}-%{release}
Requires: tpm2-abrmd-man = %{version}-%{release}

%description bin
bin components for the tpm2-abrmd package.


%package config
Summary: config components for the tpm2-abrmd package.
Group: Default

%description config
config components for the tpm2-abrmd package.


%package data
Summary: data components for the tpm2-abrmd package.
Group: Data

%description data
data components for the tpm2-abrmd package.


%package dev
Summary: dev components for the tpm2-abrmd package.
Group: Development
Requires: tpm2-abrmd-lib = %{version}-%{release}
Requires: tpm2-abrmd-bin = %{version}-%{release}
Requires: tpm2-abrmd-data = %{version}-%{release}
Provides: tpm2-abrmd-devel = %{version}-%{release}

%description dev
dev components for the tpm2-abrmd package.


%package lib
Summary: lib components for the tpm2-abrmd package.
Group: Libraries
Requires: tpm2-abrmd-data = %{version}-%{release}
Requires: tpm2-abrmd-license = %{version}-%{release}

%description lib
lib components for the tpm2-abrmd package.


%package license
Summary: license components for the tpm2-abrmd package.
Group: Default

%description license
license components for the tpm2-abrmd package.


%package man
Summary: man components for the tpm2-abrmd package.
Group: Default

%description man
man components for the tpm2-abrmd package.


%prep
%setup -q -n tpm2-abrmd-2.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541140092
%configure --disable-static --with-dbuspolicydir=/usr/share/dbus-1/system.d \
--with-systemdsystemunitdir=/usr/lib/systemd/system \
--with-systemdpresetdir=/usr/lib/systemd/system-preset \
--datarootdir=/usr/share
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1541140092
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tpm2-abrmd
cp LICENSE %{buildroot}/usr/share/package-licenses/tpm2-abrmd/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tpm2-abrmd

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system-preset/tpm2-abrmd.preset
/usr/lib/systemd/system/tpm2-abrmd.service

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system-services/com.intel.tss2.Tabrmd.service
/usr/share/dbus-1/system.d/tpm2-abrmd.conf

%files dev
%defattr(-,root,root,-)
/usr/include/tss2/tss2-tcti-tabrmd.h
/usr/lib64/libtss2-tcti-tabrmd.so
/usr/lib64/pkgconfig/tss2-tcti-tabrmd.pc
/usr/share/man/man3/Tss2_Tcti_Tabrmd_Init.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtss2-tcti-tabrmd.so.0
/usr/lib64/libtss2-tcti-tabrmd.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tpm2-abrmd/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/tss2-tcti-tabrmd.7
/usr/share/man/man8/tpm2-abrmd.8
